# Generated by Django 5.1.7 on 2026-03-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking'),
        ),
    ]
